[tool.poetry]
name = "dasf"
version = "1.0"
description = "DASF is an Accelerated Framework for Machine Learning"
authors = ["Julio Faracco <jcfaracco@gmail.com>"]
maintainers = ["Julio Faracco <jcfaracco@gmail.com>"]
license = "MIT"
homepage = "https://github.com/lmcad-unicamp/dasf-core"
repository = "https://github.com/lmcad-unicamp/dasf-core"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Operating System :: OS Independent",
    "Development Status :: 1 - Planning",
    "Environment :: GPU :: NVIDIA CUDA",
]
readme="README.md"
exclude = ["tests/*", "docs/*"]

[tool.poetry.dependencies]
dask = "*"
dask_cuda = "*"
dask_jobqueue = "*"
dask_memusage = "*"
dask_ml = "*"
dask-pytorch-ddp = "*"
GPUtil = "*"
hdbscan = "*"
ipympl = "*"
matplotlib = "*"
prefect = "~=1.2.1"
protobuf = "~=3.20.1"
psutil = "*"
python = "^3.8"
pytorch-lightning = "*"
sklearn = "*"
torchvision = "*"
wget = "*"

xpysom = { git = "https://github.com/jcfaracco/xpysom/", branch = "dask2" }

[tool.poetry.dev-dependencies]
flake8 = "*"
mock = "*"
parameterized = "*"
pytest = "*"
wheel = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
