name: Continuous Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: add python 3.10 when it is faster than others
        python-version: ["3.8", "3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry build
          pip install dist/*.whl flake8 pytest mock parameterized
          pip install -i https://test.pypi.org/simple/ XPySom-dask
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 dasf/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 dasf/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run test cases
        run: |
          pytest tests/
