name: Docker Deploy

on:
  push:
    branches:    
      - releases
    tags:
      - '*'

jobs:
  push_to_registries:
    name: Push Docker image
    runs-on: ubuntu-latest
    environment: continuous_test
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        devices: ['cpu', 'gpu']

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Install requirements
        run: |
          pip3 install --user hpccm

      - name: Build from scratch
        run: |
          pushd build
          ./build_container.sh --device ${{ matrix.devices }} --format docker
          popd

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: jcfaracco/dasf
