name: Docker Deploy

on:
  push:
    branches:    
      - main
    tags:
      - '*'

jobs:
  push_to_registries:
    name: Push Docker image
    runs-on: ubuntu-latest
    environment: continuous_test
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build from scratch
        run: |
          apt update && apt install python3-pip && pip3 install hpccm
          pushd build
          ./build_container --device cpu --format docker
          popd
